[project]
name = "Marifer"
version = "0.0.2"
description = "Please read readme.md and license.txt!"
requires-python = "==3.12.9"
dependencies = [
    "apache-beam",
    "matplotlib",
    "mlcroissant",
    "rdkit",
    "tensorflow-cpu",
    "tensorflow-datasets"
]
