[project]
name = "Marifer"
version = "0.0.1"
description = "Molecule Generation!"
requires-python = "==3.12.9"
dependencies = [
    "apache-beam",
    "matplotlib",
    "mlcroissant",
    "rdkit",
    "scikit-learn",
    "tensorflow-cpu",
    "tensorflow-datasets"
]
