[project]
name = "Marifer"
version = "0.0.1"
description = "???"
requires-python = "==3.12.9"
dependencies = [
    "apache-beam",
    "mlcroissant",
    "rdkit",
    "tensorflow-cpu",
    "tensorflow-datasets",
]
