[project]
name = "testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apache-beam>=2.63.0",
    "mlcroissant>=1.0.14",
    "tensorflow>=2.18.0",
    "tfds-nightly>=4.9.7.dev202503060044",
]
